default_install_hook_types: [commit-msg, pre-commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        stages: [pre-commit]
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: check-json
        stages: [pre-commit]
      - id: check-yaml
        stages: [pre-commit]
        args:
          - --unsafe
      - id: check-symlinks
        stages: [pre-commit]
      - id: detect-aws-credentials
        stages: [pre-commit]
        args:
          - --allow-missing-credentials
      - id: check-added-large-files
        stages: [pre-commit]
      - id: detect-private-key
        stages: [pre-commit]

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 3.6.0
    hooks:
      - id: editorconfig-checker
        stages: [pre-commit]

  - repo: https://github.com/tofuutils/pre-commit-opentofu
    rev: v2.2.2
    hooks:
      - id: tofu_fmt
        stages: [pre-commit]
      - id: tofu_tflint
        stages: [pre-commit]
        args:
          - --args=--recursive
      - id: tofu_trivy
        stages: [pre-commit]
        args:
          - --args=--severity HIGH,CRITICAL
          - --args=--skip-dirs '**/.terraform'

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [] # optional: list of Conventional Commits types to allow e.g. [feat, fix, ci, chore, test]

  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.21.0"
    hooks:
      - id: terraform-docs-system
        stages: [pre-commit]
        args: [
          "--config=.terraform-docs.yml",
          "."
        ]
